package com.riguz.jb.model.core;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("counter", "COUNTER_ID", Counter.class);
		arp.addMapping("filter", "FILTER_ID", Filter.class);
		arp.addMapping("role", "ROLE_ID", Role.class);
		arp.addMapping("token", "TOKEN_ID", Token.class);
		// Composite Primary Key order: ACCOUNT_STATUS,USER_ID
		arp.addMapping("user", "ACCOUNT_STATUS,USER_ID", User.class);
		arp.addMapping("user_to_role", "USER_TO_ROLE_ID", UserToRole.class);
	}
}

