package com.riguz.jb.model.core;

import com.riguz.jb.model.core.base.BaseCounter;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Counter extends BaseCounter<Counter> {
	public static final Counter dao = new Counter();
	public enum FIELD {
		COUNTER_ID("COUNTER_ID"),
		NAME("NAME"),
		VALUE("VALUE"),
		REMARK("REMARK"),
		COUNTER_STATUS("COUNTER_STATUS"),
		STEP("STEP"),
		MAX_VALUE("MAX_VALUE"),
		RECYCLE("RECYCLE"),
		START("START"),
		FROM_DATE("FROM_DATE"),
		THRU_DATE("THRU_DATE"),
		CREATED_DATE("CREATED_DATE"),
		LAST_UPDATED_DATE("LAST_UPDATED_DATE");

		final String field;

		private FIELD(String field) {
			this.field = field;
		}
	}
}
