package com.riguz.jb.model.core;

import com.riguz.jb.model.core.base.BaseRole;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();
	public enum FIELD {
		ROLE_ID("ROLE_ID"),
		IDENT("IDENT"),
		NAME("NAME"),
		FROM_DATE("FROM_DATE"),
		THRU_DATE("THRU_DATE"),
		CREATED_DATE("CREATED_DATE"),
		LAST_UPDATED_DATE("LAST_UPDATED_DATE"),
		ROLE_STATUS("ROLE_STATUS"),
		REMARK("REMARK"),
		RESERVE("RESERVE");

		final String field;

		private FIELD(String field) {
			this.field = field;
		}
	}
}
