package com.riguz.jb.model.core;

import com.riguz.jb.model.core.base.BaseUserToRole;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserToRole extends BaseUserToRole<UserToRole> {
	public static final UserToRole dao = new UserToRole();
	public enum FIELD {
		USER_TO_ROLE_ID("USER_TO_ROLE_ID"),
		USER_ID("USER_ID"),
		ROLE_ID("ROLE_ID"),
		FROM_DATE("FROM_DATE"),
		THRU_DATE("THRU_DATE"),
		CREATED_DATE("CREATED_DATE"),
		LAST_UPDATED_DATE("LAST_UPDATED_DATE");

		final String field;

		private FIELD(String field) {
			this.field = field;
		}
	}
}
