package com.riguz.jb.model.user;

import com.riguz.jb.model.user.base.BasePerson;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Person extends BasePerson<Person> {
	public static final Person dao = new Person();
	public enum FIELD {
		id("id"),
		name("name"),
		remark("remark");

		final String field;

		private FIELD(String field) {
			this.field = field;
		}
	}
}
