package com.riguz.jb.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseToken<M extends BaseToken<M>> extends Model<M> implements IBean {

	public void setTokenId(java.lang.String tokenId) {
		set("TOKEN_ID", tokenId);
	}

	public java.lang.String getTokenId() {
		return get("TOKEN_ID");
	}

	public void setToken(java.lang.String token) {
		set("TOKEN", token);
	}

	public java.lang.String getToken() {
		return get("TOKEN");
	}

	public void setTokenType(java.lang.String tokenType) {
		set("TOKEN_TYPE", tokenType);
	}

	public java.lang.String getTokenType() {
		return get("TOKEN_TYPE");
	}

	public void setFromDate(java.util.Date fromDate) {
		set("FROM_DATE", fromDate);
	}

	public java.util.Date getFromDate() {
		return get("FROM_DATE");
	}

	public void setThurDate(java.util.Date thurDate) {
		set("THUR_DATE", thurDate);
	}

	public java.util.Date getThurDate() {
		return get("THUR_DATE");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("CREATED_DATE", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("CREATED_DATE");
	}

	public void setLastUpdatedDate(java.util.Date lastUpdatedDate) {
		set("LAST_UPDATED_DATE", lastUpdatedDate);
	}

	public java.util.Date getLastUpdatedDate() {
		return get("LAST_UPDATED_DATE");
	}

	public void setExpiresIn(java.lang.Integer expiresIn) {
		set("EXPIRES_IN", expiresIn);
	}

	public java.lang.Integer getExpiresIn() {
		return get("EXPIRES_IN");
	}

	public void setRemark(java.lang.String remark) {
		set("REMARK", remark);
	}

	public java.lang.String getRemark() {
		return get("REMARK");
	}

	public String getTableName() {
		return "token";
	}

}
