package com.riguz.jb.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.String userId) {
		set("USER_ID", userId);
	}

	public java.lang.String getUserId() {
		return get("USER_ID");
	}

	public void setLoginName(java.lang.String loginName) {
		set("LOGIN_NAME", loginName);
	}

	public java.lang.String getLoginName() {
		return get("LOGIN_NAME");
	}

	public void setPassword(java.lang.String password) {
		set("PASSWORD", password);
	}

	public java.lang.String getPassword() {
		return get("PASSWORD");
	}

	public void setEmail(java.lang.String email) {
		set("EMAIL", email);
	}

	public java.lang.String getEmail() {
		return get("EMAIL");
	}

	public void setLastLoginIp(java.lang.String lastLoginIp) {
		set("LAST_LOGIN_IP", lastLoginIp);
	}

	public java.lang.String getLastLoginIp() {
		return get("LAST_LOGIN_IP");
	}

	public void setLastLoginDate(java.util.Date lastLoginDate) {
		set("LAST_LOGIN_DATE", lastLoginDate);
	}

	public java.util.Date getLastLoginDate() {
		return get("LAST_LOGIN_DATE");
	}

	public void setLoginIp(java.lang.String loginIp) {
		set("LOGIN_IP", loginIp);
	}

	public java.lang.String getLoginIp() {
		return get("LOGIN_IP");
	}

	public void setLoginDate(java.util.Date loginDate) {
		set("LOGIN_DATE", loginDate);
	}

	public java.util.Date getLoginDate() {
		return get("LOGIN_DATE");
	}

	public void setTokenId(java.lang.String tokenId) {
		set("TOKEN_ID", tokenId);
	}

	public java.lang.String getTokenId() {
		return get("TOKEN_ID");
	}

	public void setFailTotal(java.lang.Integer failTotal) {
		set("FAIL_TOTAL", failTotal);
	}

	public java.lang.Integer getFailTotal() {
		return get("FAIL_TOTAL");
	}

	public void setAccountStatus(java.lang.String accountStatus) {
		set("ACCOUNT_STATUS", accountStatus);
	}

	public java.lang.String getAccountStatus() {
		return get("ACCOUNT_STATUS");
	}

	public void setAdditionalId(java.lang.String additionalId) {
		set("ADDITIONAL_ID", additionalId);
	}

	public java.lang.String getAdditionalId() {
		return get("ADDITIONAL_ID");
	}

	public void setEmailStatus(java.lang.String emailStatus) {
		set("EMAIL_STATUS", emailStatus);
	}

	public java.lang.String getEmailStatus() {
		return get("EMAIL_STATUS");
	}

	public void setPortrait(java.lang.String portrait) {
		set("PORTRAIT", portrait);
	}

	public java.lang.String getPortrait() {
		return get("PORTRAIT");
	}

	public void setReserve(java.lang.String reserve) {
		set("RESERVE", reserve);
	}

	public java.lang.String getReserve() {
		return get("RESERVE");
	}

	public void setRemark(java.lang.String remark) {
		set("REMARK", remark);
	}

	public java.lang.String getRemark() {
		return get("REMARK");
	}

	public void setFromDate(java.util.Date fromDate) {
		set("FROM_DATE", fromDate);
	}

	public java.util.Date getFromDate() {
		return get("FROM_DATE");
	}

	public void setThruDate(java.util.Date thruDate) {
		set("THRU_DATE", thruDate);
	}

	public java.util.Date getThruDate() {
		return get("THRU_DATE");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("CREATED_DATE", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("CREATED_DATE");
	}

	public void setLastUpdatedDate(java.util.Date lastUpdatedDate) {
		set("LAST_UPDATED_DATE", lastUpdatedDate);
	}

	public java.util.Date getLastUpdatedDate() {
		return get("LAST_UPDATED_DATE");
	}

	public void setAccountType(java.lang.String accountType) {
		set("ACCOUNT_TYPE", accountType);
	}

	public java.lang.String getAccountType() {
		return get("ACCOUNT_TYPE");
	}

	public void setLdapCn(java.lang.String ldapCn) {
		set("LDAP_CN", ldapCn);
	}

	public java.lang.String getLdapCn() {
		return get("LDAP_CN");
	}

	public void setRealName(java.lang.String realName) {
		set("REAL_NAME", realName);
	}

	public java.lang.String getRealName() {
		return get("REAL_NAME");
	}

	public void setGender(java.lang.String gender) {
		set("GENDER", gender);
	}

	public java.lang.String getGender() {
		return get("GENDER");
	}

	public String getTableName() {
		return "user";
	}

}
