package com.riguz.jb.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFilter<M extends BaseFilter<M>> extends Model<M> implements IBean {

	public void setFilterId(java.lang.String filterId) {
		set("FILTER_ID", filterId);
	}

	public java.lang.String getFilterId() {
		return get("FILTER_ID");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}

	public java.lang.String getName() {
		return get("NAME");
	}

	public void setOrder(java.lang.Integer order) {
		set("ORDER", order);
	}

	public java.lang.Integer getOrder() {
		return get("ORDER");
	}

	public void setUrl(java.lang.String url) {
		set("URL", url);
	}

	public java.lang.String getUrl() {
		return get("URL");
	}

	public void setRules(java.lang.String rules) {
		set("RULES", rules);
	}

	public java.lang.String getRules() {
		return get("RULES");
	}

	public void setFromDate(java.util.Date fromDate) {
		set("FROM_DATE", fromDate);
	}

	public java.util.Date getFromDate() {
		return get("FROM_DATE");
	}

	public void setThruDate(java.util.Date thruDate) {
		set("THRU_DATE", thruDate);
	}

	public java.util.Date getThruDate() {
		return get("THRU_DATE");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("CREATED_DATE", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("CREATED_DATE");
	}

	public void setLastUpdatedDate(java.util.Date lastUpdatedDate) {
		set("LAST_UPDATED_DATE", lastUpdatedDate);
	}

	public java.util.Date getLastUpdatedDate() {
		return get("LAST_UPDATED_DATE");
	}

	public void setFilterStatus(java.lang.String filterStatus) {
		set("FILTER_STATUS", filterStatus);
	}

	public java.lang.String getFilterStatus() {
		return get("FILTER_STATUS");
	}

	public void setRemark(java.lang.String remark) {
		set("REMARK", remark);
	}

	public java.lang.String getRemark() {
		return get("REMARK");
	}

	public String getTableName() {
		return "filter";
	}

}
