package com.riguz.jb.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCounter<M extends BaseCounter<M>> extends Model<M> implements IBean {

	public void setCounterId(java.lang.String counterId) {
		set("COUNTER_ID", counterId);
	}

	public java.lang.String getCounterId() {
		return get("COUNTER_ID");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}

	public java.lang.String getName() {
		return get("NAME");
	}

	public void setValue(java.lang.Integer value) {
		set("VALUE", value);
	}

	public java.lang.Integer getValue() {
		return get("VALUE");
	}

	public void setRemark(java.lang.String remark) {
		set("REMARK", remark);
	}

	public java.lang.String getRemark() {
		return get("REMARK");
	}

	public void setCounterStatus(java.lang.Integer counterStatus) {
		set("COUNTER_STATUS", counterStatus);
	}

	public java.lang.Integer getCounterStatus() {
		return get("COUNTER_STATUS");
	}

	public void setStep(java.lang.Integer step) {
		set("STEP", step);
	}

	public java.lang.Integer getStep() {
		return get("STEP");
	}

	public void setMaxValue(java.lang.Integer maxValue) {
		set("MAX_VALUE", maxValue);
	}

	public java.lang.Integer getMaxValue() {
		return get("MAX_VALUE");
	}

	public void setRecycle(java.lang.String recycle) {
		set("RECYCLE", recycle);
	}

	public java.lang.String getRecycle() {
		return get("RECYCLE");
	}

	public void setStart(java.lang.Integer start) {
		set("START", start);
	}

	public java.lang.Integer getStart() {
		return get("START");
	}

	public void setFromDate(java.util.Date fromDate) {
		set("FROM_DATE", fromDate);
	}

	public java.util.Date getFromDate() {
		return get("FROM_DATE");
	}

	public void setThruDate(java.util.Date thruDate) {
		set("THRU_DATE", thruDate);
	}

	public java.util.Date getThruDate() {
		return get("THRU_DATE");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("CREATED_DATE", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("CREATED_DATE");
	}

	public void setLastUpdatedDate(java.util.Date lastUpdatedDate) {
		set("LAST_UPDATED_DATE", lastUpdatedDate);
	}

	public java.util.Date getLastUpdatedDate() {
		return get("LAST_UPDATED_DATE");
	}

	public String getTableName() {
		return "counter";
	}

}
